version: '3.8'
services:
  ocserv:
    image: aold619/ocserv:latest
    container_name: ocserv
    # hostname: vpn.example.com
    env_file:
      - ./.env
    ports:
      - 443:443
      - 443:443/udp
    # volumes:
    #   - ./ocserv:/etc/ocserv
    #   - ./letsencrypt:/etc/letsencrypt
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    #restart: on-failure
